[global]
timezone = "Australia/Sydney"

[sergo]
handler_engine = "sergo.handler.FastAPIHandler"
database_engine = "sergo.connection.postgres.PostgresConnection"
query_engine = "sergo.query.postgres.PostgresQuery"
log_level = "INFO"

[database]
host = ""
name = ""
user = ""
pass = ""
port = 0

[environment]
